### PR TITLE
Remove empty scrollbars from all repos

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

Follow up on Ivan's work - extending the replacement of `overflow: scroll` to `auto` across all instances in the different apps.

## Related issues

Contributes to #441

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by morden35** [comment]
Hey Mahmoud! I ran this locally to check it out. Did it change the guidance page by chance (or did it always look like this?). In particular, it looks like the Guidance part of the page has been 'pushed up' closer to the headers. What do you think?

Screenshot 2023-03-03 at 3 45 19 PM

**Comment by morden35** [comment]
But it does look like the scroll bars we were seeing before are gone so that's great!

Screenshot 2023-03-03 at 3 49 10 PM

**Comment by morden35** [comment]
However I do have a larger (Google Chrome) scroll bar on this entire page, even though there is no where to scroll.
Screenshot 2023-03-03 at 3 50 33 PM

**Comment by mxosman** [comment]
> Hey Mahmoud! I ran this locally to check it out. Did it change the guidance page by chance (or did it always look like this?). In particular, it looks like the Guidance part of the page has been 'pushed up' closer to the headers. What do you think?
> 
> Screenshot 2023-03-03 at 3 45 19 PM

I noticed that everything was pushed up too when I was working off of main today... I'll look into that!

If you pull the latest main on the frontend - those scrollbars in this screenshot should be gone entirely as I removed the container itself.

**Comment by mxosman** [comment]
> However I do have a larger (Google Chrome) scroll bar on this entire page, even though there is no where to scroll. Screenshot 2023-03-03 at 3 50 33 PM

I think this one makes sense to me because the page underneath of the modal is scrollable and I believe it's referencing that. When the modal is open, all we do is prevent scrolling on the body of the page so you don't have a situation where the modal is open and you can still scroll on everything underneath it - if that makes sense.

**Comment by morden35** [comment]
> I think this one makes sense to me because the page underneath of the modal is scrollable and I believe it's referencing that. When the modal is open, all we do is prevent scrolling on the body of the page so you don't have a situation where the modal is open and you can still scroll on everything underneath it - if that makes sense.

Got it, makes sense!

**Comment by mxosman** [comment]
> > Hey Mahmoud! I ran this locally to check it out. Did it change the guidance page by chance (or did it always look like this?). In particular, it looks like the Guidance part of the page has been 'pushed up' closer to the headers. What do you think?
> 
> I noticed that everything was pushed up too when I was working off of main today... I'll look into that!
> 

OK! I think I figured out what was going on - there was a `height` property clash in the mergers this week - fixed it here with this commit https://github.com/Recidiviz/justice-counts/pull/465/commits/26078121d99efd93e998c4309e7053e6bd132347

**Review by lilidworkin — APPROVED** [review]
Awesome! Thanks so much @mxosman for going out of your way to catch some of these missing ones! And thanks to @morden35 for helping to test!

**Pull request merged**
