### PR TITLE
Settings: Metric Configuration: Playtesting Followups - Selection States (2/n)

### LINKED ISSUE #109: [Frontend] Metric Configuration - Playtesting Followups (7/n)

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

Updates the hover/selected states and adds new arrow SVG.

https://user-images.githubusercontent.com/59492998/197638165-237eed96-a4b1-4dd8-a3dd-3468a5bfe4b3.mov

## Related issues

Closes #109 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by lilidworkin — COMMENTED** [review]
Is the Active/Hover state supposed to apply to "Total Staff" or just the breakdowns? Right now the treatment is making "Total Staff" look like an input field, which is confusing. Can you check with @hobuobi ? Thanks! Otherwise, looks perfect.

**Comment by mxosman** [comment]
> Is the Active/Hover state supposed to apply to "Total Staff" or just the breakdowns? Right now the treatment is making "Total Staff" look like an input field, which is confusing. Can you check with @hobuobi ? Thanks! Otherwise, looks perfect.

Yeah - per the Figma link he shared with the updates, the overall metric receives the same treatment:
https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=4428%3A9603

Screen Shot 2022-10-25 at 11 34 55 AM

**Review by lilidworkin — APPROVED** [review]
Sounds good, thanks for confirming! I'll be curious what other folks think of that treatment during playtesting.

**Comment by mxosman** [comment]
> Sounds good, thanks for confirming! I'll be curious what other folks think of that treatment during playtesting.

I do agree though on first look that it looked like an input.

**Review by terryttsai — APPROVED** [review]

**Pull request merged**
