### PR TITLE
Nit #9: Change visual treatment for Agency Settings modal

### LINKED ISSUE #698: Nit #9: Change visual treatment for Agency Settings modal
Item 9 in this [Figma file](https://www.figma.com/file/0UZOuDCrwGqWLKOhAyvGbc/Forrest's-First-Figma-File-(FFFF)?type=design&node-id=1173%3A45776&t=vmxUwNJ53SY7d0fk-1)

### PR DESCRIPTION
**Pull request by ivan-kishko**
## Description of the change

> Transparent background for agency settings edit mode modals

## Type of change
Type: Non-breaking refactor

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #698 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by mxosman** [comment]
Nice! I just want to clarify the behavior when these modals appear - right now it appears as though when you click on a setting, that div is popping out of its original position and the other settings are filling in the empty space. Is this the desired behavior (cc @forrestkim00 ) or would it be better for each modal to be a more independent pop out (space beneath the modal doesn't change)? LMK if I'm not making sense - here's a demo of what I'm referring to (observe behind the modal):

https://github.com/Recidiviz/justice-counts/assets/59492998/f0055770-1f4d-4724-8542-5f283cc253e5

**Comment by ivan-kishko** [comment]
> Nice! I just want to clarify the behavior when these modals appear - right now it appears as though when you click on a setting, that div is popping out of its original position and the other settings are filling in the empty space. Is this the desired behavior (cc @forrestkim00 ) or would it be better for each modal to be a more independent pop out (space beneath the modal doesn't change)? LMK if I'm not making sense - here's a demo of what I'm referring to (observe behind the modal):
> 
>  Screen.Recording.2023-06-22.at.3.51.22.PM.mov

Hello @mxosman I an not sure I get the idea of what you are saying but this modal is basically 1 omponent with diff props that is why it behaves the same way no matter what setting you choose

**Comment by lilidworkin** [comment]
I'm also not 100% sure I follow, but @mxosman maybe start a thread in a shared channel with Forrest + Ivan (is Forrest in the inobright channel) to clarify with him? (Not sure if Forrest checks GH regularly)

**Comment by forrestkim00** [comment]
@mxosman Great callout! If I understood you correctly then the latter is intended. So everything underneath the scrim stays the same. LMK if this clarifies things!

**Comment by mxosman** [comment]
Ah - yeah, this is tough to explain clearly. Forrest, I believe you understood my rambling correctly!

Here's a clearer video - I added some opacity to the modal so you can see what's happening beneath and added a red border of the area to look for. 

Basically, when you click to edit Agency Information or Agency Homepage URL or Jurisdictions, the modal pops up correctly, but the section where you clicked "Edit" underneath (think 1-2 z-indexes underneath the modal) is removed from the DOM and the other sections take up the space - which looks a bit jerky.

E.g. - when you click on "Edit description ->" in the "Agency Information", the modal pops up, but the "Agency Information" section underneath is no longer in the DOM, so the other two sections "Agency Homepage URL" and "Jurisdictions" move up to take that empty space.

https://github.com/Recidiviz/justice-counts/assets/59492998/adb385b0-b35d-419b-a118-2ddce04ed099

**Comment by forrestkim00** [comment]
Ah ok! That was not a stylistic choice and we should not remove the section from the DOM underneath. Thanks for clarifying!

**Comment by ivan-kishko** [comment]
I got it. When background was not transparent it did not actually matter but now it is visible, will fix in no time

**Comment by ivan-kishko** [comment]
@mxosman @lilidworkin @forrestkim00 [33f3872](https://github.com/Recidiviz/justice-counts/pull/734/commits/33f3872664d7f9949bb7db6ace37c09786bcc248) Here you go!)

**Review by mxosman — APPROVED** [review]
Amazing! Thank you, Ivan! Yeah - it was totally not noticeable until now. Looks great to me!

**Pull request merged**
