### PR TITLE
[Justice Counts] added json file with all 24329 jurisdictions

### PR DESCRIPTION
**Pull request by morden35**
## Description of the change

Adding a json file with all 24,329 jurisdictions (states, counties, and county subdivisions). This will allow the frontend to implement a search box so agencies can select which jurisdictions are included and excluded from their agency.

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Related to [#18183](https://github.com/Recidiviz/recidiviz-data/pull/18183)
Related to [#17661](https://github.com/Recidiviz/recidiviz-data/issues/17661)

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by mxosman** [comment]
Wow! This JSON is a beast! Just wanted to say thank you for all of it!  🙌

**Review by lilidworkin — APPROVED** [review]
Awesome!

@ivan-kishko , can you double check and confirm that this works for you, and if so you can accept the PR too? Thanks!

**Comment by ivan-kishko** [comment]
Hello!) Thanks for a PR. 1 question - can we add a field name for each entry. I know there are county_name state_name and so on but to be able to search I need a name field that is not null inside every entry. so if it is type: state then name =  state_name, if it is type: county then name =  county_name. If not then I can manipulate this data by myself and make it look like I need, considering I could need more changes maybe you decide it to leave it like that and further changes I would have to do on a frontend. Thank you!

**Comment by lilidworkin** [comment]
I think that's a reasonable request! @morden35 what do you think?

**Comment by morden35** [comment]
> Hello!) Thanks for a PR. 1 question - can we add a field name for each entry. I know there are county_name state_name and so on but to be able to search I need a name field that is not null inside every entry. so if it is type: state then name = state_name, if it is type: county then name = county_name. If not then I can manipulate this data by myself and make it look like I need, considering I could need more changes maybe you decide it to leave it like that and further changes I would have to do on a frontend. Thank you!

Yes, I can absolutely do this!

**Comment by morden35** [comment]
@ivan-kishko I added 'area_name' field! Let me know what you think

**Comment by ivan-kishko** [comment]
> @ivan-kishko I added 'area_name' field! Let me know what you think

Thanks! look great!. One question @lilidworkin I guess maybe for you, county_subdivision for UI is it equals to city?

**Review by ivan-kishko — APPROVED** [review]

**Comment by lilidworkin** [comment]
Great question @ivan-kishko. For now, yes, you can do that. @hobuobi , @agronomic I think technically we want the UI to support "states", "counties", and "county subdivisions", not "cities". Could we just rename "city" to "county subdivision"?

**Pull request merged**
