### PR TITLE
[Justice Counts] Metric Settings Copy Changes

### PR DESCRIPTION
**Pull request by morden35**
## Description of the change

Copy changes based on feedback from Matt from CSG.

report -> share
Screenshot 2023-05-11 at 2 36 36 PM

disaggregations -> breakdowns
Screenshot 2023-05-11 at 2 37 05 PM

datapoint -> metric
Screenshot 2023-05-11 at 2 37 51 PM

datapoint -> breakdown
Screenshot 2023-05-11 at 2 38 21 PM

datapoints -> metrics and breakdowns
Screenshot 2023-05-11 at 2 38 44 PM

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Related to #630

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by morden35** [comment]
Please hold review! Currently debugging an error

**Review by nichelle-hall — APPROVED** [review]
LGTM!

**Review by lilidworkin — COMMENTED** [review]
Copy changes look great @morden35 ! Thanks for all the screenshots!

With regard to the Annually change -- as commented on your other PR, I think ideally we would just change where it appears printed out in the UI, and not worry about what enum values we're using behind the scenes, etc. If that's tricky, I'd say we just remove this change for now and get all the other copy changes in for now.

Edit: for instance, we'd need to look for places like this `metric.customFrequency?.toLowerCase()` and replace that with some logic. We could even have a helper function that takes in metric.customFrequency and returns either ANNUALLY or MONTHLY and just call instead of wherever we are printing `metric.customFrequency`.

**Comment by morden35** [comment]
> Copy changes look great @morden35 ! Thanks for all the screenshots!
> 
> With regard to the Annually change -- as commented on your other PR, I think ideally we would just change where it appears printed out in the UI, and not worry about what enum values we're using behind the scenes, etc. If that's tricky, I'd say we just remove this change for now and get all the other copy changes in for now.
> 
> Edit: for instance, we'd need to look for places like this `metric.customFrequency?.toLowerCase()` and replace that with some logic. We could even have a helper function that takes in metric.customFrequency and returns either ANNUALLY or MONTHLY and just call instead of wherever we are printing `metric.customFrequency`.

This all makes sense! Let me give this another try today. I will separate the 'annually' stuff out into it's own pr.

**Review by lilidworkin — APPROVED** [review]
Great!

**Pull request merged**
