### PR TITLE
[Justice Counts] Replace curly with straight apostrophe in agency name

### PR DESCRIPTION
**Pull request by morden35**
## Description of the change

Replace curly apostrophes (`’`) with straight apostrophes (`'`) in agency names upon creation/editing in the admin panel.

#### How I Tested
I created a new agency that contained curly apostrophes within the agency name. The agency was properly saved in the database with straight apostrophes. I also attempted to edit the agency name and add in a curly apostrophe. I confirmed that this was saved with the expected straight apostrophe.

Screenshot 2024-05-13 at 4 07 14 PM

Screenshot 2024-05-13 at 4 07 49 PM

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Related to #28872

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by morden35** [comment]
Based on the following sql query, we should update the following agencies (backfill fix):
`select id, name from source where name like '%’%';`
results in
```
   97 | Franklin County Public Defender’s Office
   99 | Story County Attorney’s Office
  100 | Franklin County Prosecutor’s Office
  123 | Columbus City Attorney’s Office
  663 | Aileen O’Connor Residential House
 1526 | Hamilton County Sheriff’s Office
 1530 | Thurston County Prosecuting Attorney’s Office
 1531 | Thurston County Sheriff’s Office
  127 | Cass County Sheriff’s Department
```

**Review by mxosman — APPROVED** [review]
Thank you so much, Michelle!

**Review by lilidworkin — COMMENTED** [review]
Awesome, thank you Michelle! You have the green light from me to update those names and then just give CSG (esp Matt) a heads up after so we knows we knocked this out :)

**Comment by morden35** [comment]
> Awesome, thank you Michelle! You have the green light from me to update those names and then just give CSG (esp Matt) a heads up after so we knows we knocked this out :)

Sounds good and will do! I will wait for this pr to make it into the prod deploy before doing the backwards change

**Comment by morden35** [comment]
Backwards changes are complete and CSG has been notified. The sql query above now result in 0 rows

**Pull request merged**
