### PR TITLE
[Publisher] Styling fix for long system names

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

Quick follow up to @morden35's snake case fix (thank you again so much!) - adjusts the styling so the system name doesn't wrap:

From:
Screenshot 2023-08-15 at 11 11 01 AM

To:
Screenshot 2023-08-15 at 11 14 00 AM

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by morden35** [comment]
Nice! Out of curiosity, what does this look like if 5 dimensions show? (add 'Other Supervision')

**Review by lilidworkin — APPROVED** [review]
beautiful, thx!

**Comment by mxosman** [comment]
> Nice! Out of curiosity, what does this look like if 5 dimensions show? (add 'Other Supervision')

Good question - I was thinking a similar thing and made a note for myself to explore the overflow here (I don't think we ever did explore this possibility). Right now, it'll just keep extending past the right side of the task card - which I think is OK for now. Ideally, we would want these to wrap into a second row if it overflows to keep that width uniform - but will take a bit more thought and fiddling to update the CSS in the right places to get it just right.

**Comment by mxosman** [comment]
It actually wasn't too bad! 😅 

Screenshot 2023-08-15 at 11 55 33 AM

Screenshot 2023-08-15 at 12 08 13 PM

**Pull request merged**
