### PR TITLE
[Publisher][Bug] Explore Data: Breakdowns show missing data

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

> Description here

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #XXXX

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by mxosman** [comment]
Thank you for all the sleuthing @nasaownsky! I have no idea why that is happening. I think ultimately the UI shouldn't care about the ordering of things and display the accurate views. Can you dig into what we need to do in order for the UI to stay agnostic to the ordering?

**Comment by nasaownsky** [comment]
I'll try! The problem not in the UI itself, but in datapoints preparing method, which gives them wrong frequency depending on the order of the data.

**Comment by mxosman** [comment]
Sorry by UI - I was meaning the frontend in general including the datapoints prep the stores are doing. If there's a way the FE can handle these cases, that would be preferred b/c the ordering shouldn't matter on the FE - it's so strange that it's creating this kind of issue.

**Comment by mxosman** [comment]
Wait... my mind is absolutely blown! Taking a closer look shortly.

**Comment by mxosman** [comment]
Incredible sleuthing, @nasaownsky!

>by checking if datapoint actually has value we are getting rid of overlapping. Besides, only datapoints with values ​​will reach this part of that method in any case.

Can you elaborate on this part? I'm having trouble understanding why checking for the presence of a value and frequency prevents the overwriting.

**Comment by nasaownsky** [comment]
@mxosman Yes, you're right! Frequency check is unnecessary there.
Just checked it twice, comparing this change's charts with staging charts, and it seems all of them are the same. But you can also check this, so that I don't sound unfounded!

**Review by mxosman — APPROVED** [review]
> @mxosman Yes, you're right! Frequency check is unnecessary there. Just checked it twice, comparing this change's charts with staging charts, and it seems all of them are the same. But you can also check this, so that I don't sound unfounded!

Amazing - looks good to me too! One small request - can you add a comment on that `else` conditional with a brief explanation on why we're adding this for our future selves?

Absolutely incredible sleuthing, @nasaownsky! I appreciate it so much!

**Comment by nasaownsky** [comment]
Thank you @mxosman! How should we merge this one?

**Comment by mxosman** [comment]
> Thank you @mxosman! How should we merge this one?

Ah, you can rebase this on top of main and undo the injected datapoints array in the `DatapointsStore` if the rebase doesn't clear it back to this: https://github.com/Recidiviz/justice-counts/blob/8307a2d20f16a06c81ae20f75cf760cb1da530fe/publisher/src/stores/DatapointsStore.ts#L84

**Pull request merged**
