### PR TITLE
[Publisher][Admin Panel][Bug] Disable secondary Create New User flow

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

Disable secondary Create New User flow in the admin panel until the bugs in #1442 are resolved.

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Contributes to #1442 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by mxosman** [comment]
Does this feel worth doing a staging + prod deploy just to prevent more issues from folks using this flow?

**Review by lilidworkin — APPROVED** [review]
Yea! I think this is actually the right medium-long term solution, haha. Doesn't feel worth the complexity

**Comment by mxosman** [comment]
> Yea! I think this is actually the right medium-long term solution, haha. Doesn't feel worth the complexity

Thank you, Lili! Haha - I figured since this was more of a "nice-to-have" feature that it could wait a bit. Do you think it's worth doing a staging + prod deploy - or does this feel OK to wait until next Wednesday?

**Comment by lilidworkin** [comment]
@mxosman I don't feel strongly re: deploy, up to you!

**Pull request merged**
