### PR TITLE
Remove initialization of entities from updater functions in metr…

### LINKED ISSUE #217: [Frontend] [Proposed Refactor] MetricConfigStore: Separate metadata and initialization from updater functions
Within the `MetricConfigStore`, we can separate the metadata initialization logic from the functions that handle updating a metric's settings/values.

Here's Terry's suggestion:

> Instead of having updateMetricEnabledStatus handle both changing the metric enabled AND initializing metric metadata, we create a separate initializeMetric function like so:

```
  initializeMetric = (
    system: AgencySystems,
    metricKey: string,
    metadata: { [key: string]: string | number | null }
  ) => {
    const systemMetricKey = MetricConfigStore.getSystemMetricKey(
      system,
      metricKey
    );

    /** Initialize nested object for quick lookup and update and reduce re-renders */
    if (!this.metrics[systemMetricKey]) {
      this.metrics[systemMetricKey] = {};
    }

    /** Add metadata required for rendering */
    this.metrics[systemMetricKey].label = metadata.label as string;
    this.metrics[systemMetricKey].description = metadata.description as string;
    this.metrics[systemMetricKey].defaultFrequency =
      metadata.frequency as ReportFrequency;
    this.metrics[systemMetricKey].customFrequency =
      metadata.customFrequency as ReportFrequency;
    this.metrics[systemMetricKey].startingMonth = metadata.startingMonth as
      | number
      | null;
  };

  ...
  initializeMetricDefinitionSetting,
  etc.
```
> then updateMetricEnabledStatus can be simplified to just only updating the metric enabled state?"

Reference Example Commit: https://github.com/Recidiviz/justice-counts/commit/e7a5ac75147af607b0ee956ab1064bc4da6c5abd
Reference PR: https://github.com/Recidiviz/justice-counts/pull/199
Reference Discussion: https://github.com/Recidiviz/justice-counts/pull/199#discussion_r1041481991

### PR DESCRIPTION
**Pull request by ivan-kishko**
## Description of the change

> Remove initialization of entities from updater functions

## Type of change
Type: Non-breaking refactor

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #217 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by mxosman** [comment]
Thank you so much for knocking this out so quickly. I want to double check with @terryttsai because I'm trying to jog my memory on the conversation we had. Terry - is this in the ballpark of what you were suggesting? Or was it to completely remove the initialization from the updater functions and call them (initialization functions) separately? Here's a reference to the task just to help jog our memories: https://github.com/Recidiviz/justice-counts/issues/217

**Comment by terryttsai** [comment]
Thanks Ivan for the PR! I like the ideas in here.

So I looked into this and wrote up a draft PR of what I was thinking for a refactor here: https://github.com/Recidiviz/justice-counts/pull/323. Hope that explains things more, we can hop on a call and come to an agreement!

**Comment by ivan-kishko** [comment]
@terryttsai @mxosman Hello!) please check out lates commit if I got your ideas right

**Review by terryttsai — APPROVED** [review]
This looks fantastic, thanks for putting in the time and effort to entertain my thoughts 😅

**Comment by mxosman** [comment]
Thank you so much, Ivan! LGTM too - much cleaner and more organized. Thank you for proposing this refactor, @terryttsai!

I realized that my #366 PR created a small conflict here - sorry about that! All I did was add a `description` to the dimensions' `metadata` in the MetricConfigStore during initialization. Let me know if you need any help resolving - happy to push up a conflict resolution commit!

**Comment by ivan-kishko** [comment]
I resolved conflicts so let me know when I can merge this PR) Thanks!)

**Review by lilidworkin — APPROVED** [review]
Go ahead and merge, thanks so much @ivan-kishko !

**Pull request merged**
