### PR TITLE
[Publisher] Keep chart calculation regardless of screen width

### LINKED ISSUE #1398: [Publisher] Show the chart calculations in Explore Data in smaller screen widths
Instead of hiding the calculations in this narrow screen width (screenshot at 1440 width):
image

We should continue displaying these calculations regardless of screen width:
Screenshot 2024-06-18 at 10 54 01 AM

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

> Description here

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

closes #1398 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
Hi @mxosman! I removed chart calculation hiding at the top, but I noticed that under 1200px screen width these calculations showed at the bottom:

Снимок экрана 2024-06-26 в 17 15 45

So where should I preserve them, at the top or at the bottom?

**Comment by mxosman** [comment]
> Hi @mxosman! I removed chart calculation hiding at the top, but I noticed that under 1200px screen width these calculations showed at the bottom:
> 
> Снимок экрана 2024-06-26 в 17 15 45
> 
> So where should I preserve them, at the top or at the bottom?

Omg! Great catch!! Hmm... Let's lose the one on the bottom because it's harder to see in that screen width. Can we keep the one on top but move it to below the metric title as we get to 1200px?

Screenshot 2024-06-26 at 9 47 08 AM

Thank you, @nasaownsky!

**Comment by nasaownsky** [comment]
> Can we keep the one on top but move it to below the metric title as we get to 1200px?

@mxosman sure, check my changes!

**Review by mxosman — APPROVED** [review]
Fantastic! Thank you so much, @nasaownsky!

**Pull request merged**
