### PR TITLE
[Admin Panel] Add delete agency functionality

### LINKED ISSUE #1300: [Admin Panel] Make it possible to delete agencies
It's currently possible to delete users via the Admin Panel -- if you hover over the card, a red trash icon appears in the bottom right. If you click it, a confirmation modal appears.

We'd like to add the same behavior for deleting agencies! It should work similarly with the red trashcan and the confirmation modal.

Unfortunately the backend API for this does not exist yet, but for now you can imagine that there will be an endpoint `/admin/agency/<id> DELETE`, and build everything assuming that will work.

But since that endpoint won't actually work just yet, let's only show the trashcan if the user's role is AgencyTeamMemberRole.JUSTICE_COUNTS_ADMIN -- that way this won't go live yet to anyone besides us!

cc @mxosman

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Added delete agency functionality

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

closes #1300 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
Hello again, @mxosman! I'm glad to be back! 

So it seems like this should function properly, but when confirming delete it responds with 500 error. Is `/admin/agency/<id>` DELETE endpoint actually working?

**Comment by lilidworkin** [comment]
Also cc @morden35 who is oncall since this is related to latest Sentry error, I believe! Sorry about this, @nasaownsky !

**Comment by morden35** [comment]
> Also cc @morden35 who is oncall since this is related to latest Sentry error, I believe! Sorry about this, @nasaownsky !

thanks @lilidworkin! Taking a look at this now. I think we may need to adjust the backend endpoint slightly

**Comment by mxosman** [comment]
> Hello again, @mxosman! I'm glad to be back!
> 
> So it seems like this should function properly, but when confirming delete it responds with 500 error. Is DELETE `/admin/agency/<id>` endpoint actually working?

Welcome back, @nasaownsky!! Thank you so much for working on this - will try to review this later this afternoon! Thank you @lilidworkin & @morden35 for triaging the backend endpoint! LMK if I can be helpful in any way!

**Comment by morden35** [comment]
@lilidworkin @mxosman once this [pr](https://github.com/Recidiviz/recidiviz-data/pull/30395) is deployed to staging, the 500 error Ilya was seeing should be resolved!

**Comment by mxosman** [comment]
Thank you so much @morden35!!

**Comment by mxosman** [comment]
The day is running away from me - will review tomorrow morning!

**Review by mxosman — COMMENTED** [review]
Smooth as usual, @nasaownsky - no notes from me! Thank you so much!

We're still working on getting our staging deploy back up and running - I want to do a quick E2E test with this before officially approving, but consider this reviewed & approved!

**Review by mxosman — APPROVED** [review]
Deployed and tested via this link: https://mahmoudtest---publisher-web-b47yvyxs3q-uc.a.run.app/admin-panel

Works beautifully!! Thanks again, Ilya!

**Pull request merged**
