### PR TITLE
Minor branding updates

### LINKED ISSUE #369: Minor branding updates (logo, footer, etc)
In order to meet expectations with the Bureau of Justice Administration (BJA; primary funder for the project), we have to update a few things about how the Justice Counts brand appears throughout the application. Changes are detailed in Figma. 

### P0: Header + Logo

The logo in the top-left should be updated (dark blue background, with a gradient logo). Additionally, the words "Justice Counts" should be added immediately to the right of the logo. (For now, this should not appear at smaller screen sizes, though we might update this in an upcoming ticket on responsiveness.) 

navbarUpdated

### P0: Footer 
A footer should be included at the bottom of every page that includes information about the project grant, key organizations, etc. 
- The footer should not be fixed at the bottom of the page (always visible), but rather should appear once the user scrolls through all of the content on the page. Note that this might mean adjusting the positioning of some elements (for example, the note in the bottom-left about Metric Configuration in the Data Entry View). Feel free to discuss different approaches!
- The footer should be generally responsive to the screen size – if more specific guidance has not been given by the time you get to implementing this, feel free to do what is easiest. 

Group 2823

### P1: Auth0 Portal (for @lilidworkin ) 
- The logo (referenced here: https://justice-counts-web-qqec6jbn6a-uc.a.run.app/android-chrome-192x192.png) should be updated to the new gradient logo. 
- The button color should be updated to #001133. 

### P2: UI Colors
#001133 should be used as the base color for UI text, rather than #171C2B. The opacities (e.g., 60% for a lighter gray) used should be consistent with the old implementation. 
- Note that it's possible that the implementation has not defined colors by base color x opacity, in the same way that the design system in Figma does. If that's true and changing the colors would be anything more than a single line change, please skip this.

### PR DESCRIPTION
**Pull request by ivan-kishko**
## Description of the change

> Add footer to application

## Type of change
Type: Non-breaking refactor

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #369 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by ivan-kishko** [comment]
Hello all!) @agronomi, answering your slack message, I guess yeah we need some general space value between content and footer, you can say it here after you check how it looks) thanks!

**Review by hobuobi — CHANGES_REQUESTED** [review]
Looking great! 
I did notice one bug on the Bulk Upload page; while the footer looks fine, the header logo is missing and seems to be hidden underneath the main content. See attached video: 
https://www.loom.com/share/42e81e6debcd4fa986781e5740664436

**Review by hobuobi — APPROVED** [review]
Sweet, this all looks good to me! Thank you @ivan-kishko :)

**Comment by hobuobi** [comment]
Will request that someone merge this before Wednesday, as it looks like this might have external eyes on it (demo to BJA) on Wednesday.

**Pull request merged**
