### PR TITLE
new supervision template for bulk upload

### PR DESCRIPTION
**Pull request by nichelle-hall**
New supervision template for bulk upload!

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by lilidworkin — APPROVED** [review]
Thanks @nichelle-hall ! Not sure if you're already looking into this, but I think it would be good to test a few things:

* Can we successfully upload for the new / recently added Supervision subsystems, like Pretrial, etc? Can I see a screenshot or video showing what that flow looks like?
* What happens if a user tries to upload for a Supervision subsystem that they're not actually part of (i.e. haven't selected it in Agency Settings)?
* What happens if a user tries to upload aggregate data for a metric that they've said is disaggregated?
* What happens if a user tries to upload disaggregated data for a metric that they've said is aggregated?

Are there any other edge cases you can think of?

I imagine that we don't handle all of these cases right now, which is totally fine, but it would be good to know what the current behavior is, and how broken it feels, so we know what to prioritize addressing.

Thanks!

**Comment by nichelle-hall** [comment]
> Thanks @nichelle-hall ! Not sure if you're already looking into this, but I think it would be good to test a few things:
> 
> * Can we successfully upload for the new / recently added Supervision subsystems, like Pretrial, etc? Can I see a screenshot or video showing what that flow looks like?
> * What happens if a user tries to upload for a Supervision subsystem that they're not actually part of (i.e. haven't selected it in Agency Settings)?
> * What happens if a user tries to upload aggregate data for a metric that they've said is disaggregated?
> * What happens if a user tries to upload disaggregated data for a metric that they've said is aggregated?
> 
> Are there any other edge cases you can think of?
> 
> I imagine that we don't handle all of these cases right now, which is totally fine, but it would be good to know what the current behavior is, and how broken it feels, so we know what to prioritize addressing.
> 
> Thanks!


 * Can we successfully upload for the new / recently added Supervision subsystems, like Pretrial, etc? Can I see a screenshot or video showing what that flow looks like?
-- This was buggy, but I put up a fix (demonstrated with Loom) in another PR. 
 * What happens if a user tries to upload for a Supervision subsystem that they're not actually part of (i.e. haven't selected it in Agency Settings)?
-- Nothing happens and no error is surfaced. You see the same error page as if you didn't have an incorrect subsystem. 
 * What happens if a user tries to upload aggregate data for a metric that they've said is disaggregated?
-- All the disaggregated metrics will show up with missing metric errors. 
* What happens if a user tries to upload disaggregated data for a metric that they've said is aggregated?
--  The user will see a missing metric error for the aggregate metric.

**Review by lilidworkin — APPROVED** [review]
Thanks @nichelle-hall ! A few thoughts inline:

_Can we successfully upload for the new / recently added Supervision subsystems, like Pretrial, etc? Can I see a screenshot or video showing what that flow looks like?
-- This was buggy, but I put up a fix (demonstrated with Loom) in another PR._

Thank you!

_What happens if a user tries to upload for a Supervision subsystem that they're not actually part of (i.e. haven't selected it in Agency Settings)?
-- Nothing happens and no error is surfaced. You see the same error page as if you didn't have an incorrect subsystem._

Just to clarify -- does the data get saved for this subsystem? I'm not 100% sure what the "right" behavior is, can you make a task to revisit?

_What happens if a user tries to upload aggregate data for a metric that they've said is disaggregated?
-- All the disaggregated metrics will show up with missing metric errors.
What happens if a user tries to upload disaggregated data for a metric that they've said is aggregated?
-- The user will see a missing metric error for the aggregate metric._

Can you make a task for these cases? One task is fine to handle both.

**Comment by lilidworkin** [comment]
Oh @nichelle-hall you already addressed the issues! I didn't realize that. No need to make a task then. Thank you!!

**Pull request merged**
