### PR TITLE
[Publisher][Agency Settings] Add new biological sex and race & ethnicity data source questions

### LINKED ISSUE #1539: [Publisher][Agency Settings] Add new biological sex and race & ethnicity data source questions
There will be a new section added to the Agency Settings page that collects information on an agencies biological sex and race & ethnicity data sources. This section will live just before the `Jurisdictions` section. 

There will be an `Edit` button that will open a modal with one question for the biological sex data source (`What is the source of biological sex data in your system?`) and another question for the race & ethnicity data source (`What is the source of race and ethnicity data in your data system?`). Depending on the selection/answer of these questions, there will be at least one follow up question. 

* If the user `Data is collected directly by the agency` -> show the respective follow-up question: `How is biological sex data collected?` or `How are race and ethnicity data collected?`

* If the user selects `Data is received from another agency or data system` -> show the respective follow-up question: `Does your agency modify or amend biological sex data received from another agency or data
system?` or `Does your agency modify or amend race and ethnicity data received from another agency or
data system?`

* If the user selects `Other` (for any questions that have an `Other` field - including follow up questions) -> show a free text box that allows the user to describe their data source

* If the user selects `Unknown` -> don't show any follow up questions/text box

Reference: [Figma design](https://www.figma.com/design/mW9Hm6L95zpdWtq0noAdpz/Mahmoud's-Sandbox?node-id=0-109&t=orQgwKU7kcn1TqOT-4) (not to precise scale)

We'll be using the same `saveAgencySettings` method and endpoint with the following payload structure:

```
{
    "settings": [
        ...,
        {
            "setting_type": "BIOLOGICAL_SEX_RACE_ETHNICITY_DATA_SOURCE",
            "source_id": 11, // We no longer need to send this for each `setting`
            "value": {
	            "biological_sex": {
		            "source": { 
			            "value": "OTHER_AGENCY_OR_SYSTEM", // Option keys: CURRENT_AGENCY, OTHER_AGENCY_OR_SYSTEM, OTHER, UNKNOWN
			            "other_description": ""
		            },
		            "modification": { 
			            "value": "YES", // Option keys: YES, NO, OTHER, UNKNOWN
			            "other_description": ""
		            },
		            "collection_method": { 
			            "value": "", // Option keys: SELF_IDENTIFIED, STAFF_IDENTIFIED, OTHER, UNKNOWN
			            "other_description": ""
		            }
	            },
	            "race_ethnicity": {
		            "source": { 
			            "value": "OTHER",
			            "other_description": "Our source for this is Wikipedia and Google"
		            },
		            "modification": { 
			            "value": "",
			            "other_description": ""
		            },
		            "collection_method": { 
			            "value": "",
			            "other_description": ""
		            }
	            },
            },
        },
    ]
}
```

Here is the value -> key mapping:

Main question: 
* `Data is collected directly by the agency` ->  `CURRENT_AGENCY`
* `Data is received from another agency or data system` -> `OTHER_AGENCY_OR_SYSTEM`
* `Other` -> `OTHER`
* `Unknown` -> `UNKNOWN`

Follow-up questions:
* `Yes, data is verified or modified upon receipt` -> `YES`
* `No, data is stored unchanged` -> `NO`
* `Self-identified` -> `SELF_IDENTIFIED`
* `Observed or perceived by staff` -> `STAFF_IDENTIFIED`
* `Other` -> `OTHER`
* `Unknown` -> `UNKNOWN`

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Added data source UI and basic logic

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

closes #1539 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
Hi @mxosman! So i'm in the process of implementing new questions, and so far all seems good to me. Just need some polish, particularly in `handleCancelClick` and `handleCancelModalConfirm` functions (don't know why `emptyDataSourceSetting` is updating along with `currentDataSourceSetting`), but I'll figure it out. Just pushed it so you could check my changes and maybe tell me some feedback or implementation suggestions before you're OOO. Anyway, have a great time outside the office and see you in 1.5 weeks!

**Comment by nasaownsky** [comment]
Hi, Nichelle! 

Yeah, I think it has to do with the this functions I mentioned in my comment above, so will figuring this out. Thank you for great feedback!

**Comment by nasaownsky** [comment]
Hi @nichelle-hall! This should be ready for test and review now!

**Review by nichelle-hall — APPROVED** [review]
This looks great! I played around with is locally and it works perfectly.

**Comment by mxosman** [comment]
Thank you so much for your work on this @nasaownsky and for the review and testing @nichelle-hall!

I just played around with it and have the following quick thoughts and requests:
* It looks like you can't empty out a perviously saved value entered in the "Other" field - can you take another look?

https://github.com/user-attachments/assets/758be262-2847-4ee8-870a-025b793bc625

* Probably related to the above, but a user should be able to uncheck a selection for a question - can you take a look at this one as well?

https://github.com/user-attachments/assets/7848e309-d149-4670-b149-52cca5a5eff3


* @nichelle-hall - the FE doesn't seem to be clearing out previously saved values for the "Other" field - I know the BE doesn't care b/c it saves everything as a JSON, but can you remind me if this is surfaced anywhere in the dashboard API or if you think this will be an issue? If it's a non-issue, no worries! But, if it will be surfaced, then @nasaownsky I'll request that we empty out the fields and send the empty field to the BE when a user clicks away from the "Other".

https://github.com/user-attachments/assets/5228eb6b-3c82-4fd9-bdd7-856ff983f703

* Styling nit: can we undo the capitalization for the options? We can keep them in the same casing as the string.
 
Thank you so much @nasaownsky!

**Comment by nichelle-hall** [comment]
> @nichelle-hall - the FE doesn't seem to be clearing out previously saved values for the "Other" field when a user makes a different selection - I know the BE doesn't care b/c it saves everything as a JSON, but can you remind me if this is surfaced anywhere in the dashboard API or if you think this will be an issue? If it's a non-issue, no worries! But, if it will be surfaced, then @nasaownsky I'll request that we empty out the fields and send the empty field to the BE when a user clicks away from the "Other".

The "Other" Information is not surfaced anywhere on the Dashboard API. Only the URL and Agency Description Agency Settings are surfaced.

**Comment by mxosman** [comment]
> > @nichelle-hall - the FE doesn't seem to be clearing out previously saved values for the "Other" field when a user makes a different selection - I know the BE doesn't care b/c it saves everything as a JSON, but can you remind me if this is surfaced anywhere in the dashboard API or if you think this will be an issue? If it's a non-issue, no worries! But, if it will be surfaced, then @nasaownsky I'll request that we empty out the fields and send the empty field to the BE when a user clicks away from the "Other".
> 
> The "Other" Information is not surfaced anywhere on the Dashboard API. Only the URL and Agency Description Agency Settings are surfaced.

Thank you, Nichelle!

**Pull request merged**
