### PR TITLE
Agency Dashboard playtesting followups

### PR DESCRIPTION
**Pull request by terryttsai**
## Description of the change

<div>

- "24 months 2 years" becomes "4 years", "13 months" becomes "1 year 1 month"
Screen Shot 2023-01-05 at 9 47 59 AM
Screen Shot 2023-01-05 at 9 48 15 AM
Screen Shot 2023-01-05 at 9 50 28 AM
Screen Shot 2023-01-05 at 9 50 36 AM

- Fix legend in Race & Ethnicity overflow
- Add selected metric state for Select Metrics dropdown
- Fix “No reported data for this metric” placement in tablet and mobile
- Scrolling issue when navigating
- Make the url all lower case
- Fix issue with monthly values formatted as yearly (Agency 152 Readmissions show 4 2022 values)
  - I just made each bar say "month year" or "year" depending on whether that datapoint is annual, or monthly
Screen Shot 2023-01-05 at 9 48 22 AM

Screen Shot 2023-01-05 at 9 48 04 AM

- [Agency 152] Funding says 1 year of data in the overview, but the chart says No Data Available
  - The issue is that the frontend is receiving datapoints with Null values. In the aggregate case, it seems like we don't need this, but in the disaggregations case, that might be potentially useful because then we'd know what the dimensions are, even if they have no published values?
  - Or maybe we don't want the backend to serve any datapoints w only null values? Then how does the frontend know which dimensions exist?
  - Link to bug: https://dash---justice-counts-agency-dashboard-web-qqec6jbn6a-uc.a.run.app/agency/152
  - I changed my backend to point to https://dash---justice-counts-agency-dashboard-web-qqec6jbn6a-uc.a.run.app/ to verify the fix works
  - So now the overview should say No Data
- Back to Agency Overview button clickable area is too long
- Select Metrics button gap should be 8px
- Add “Close” to mobile modals

</div>

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #XXXX

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by terryttsai** [comment]
One thing to note is the change in this commit: https://github.com/Recidiviz/justice-counts/pull/270/commits/4849bcebf838d1dd21d0c8c5c247651c9622a67a

I just implemented their suggestion to always scroll to the top of the page when navigating to a different page. See https://v5.reactrouter.com/web/guides/scroll-restoration for their suggestion.

**Review by lilidworkin — COMMENTED** [review]
@terryttsai nice, thanks for knocking through all of these!

> Fix issue with monthly values formatted as yearly (Agency 152 Readmissions show 4 2022 values). I just made each bar say "month year" or "year" depending on whether that datapoint is annual, or monthly.

Would you mind adding a screenshot showing both before and after?

> [Agency 152] Funding says 1 year of data in the overview, but the chart says No Data Available

Can you explain what the bug / fix was? Was there actually data for this agency or not?

**Comment by terryttsai** [comment]
Updated the description with screenshots and an explanation for "No Data Available" bug!

**Review by lilidworkin — APPROVED** [review]
> The issue is that the frontend is receiving datapoints with Null values. In the aggregate case, it seems like we don't need this, but in the disaggregations case, that might be potentially useful because then we'd know what the dimensions are, even if they have no published values?

Got it! So filtering out the datapoints with null values was the fix.

I think this seems reasonable. An alternative is to not send datapoints with null values, but the backend sends over the dimensions separately. In fact I thought I remembered that you made that change (or something similar) previously -- does that ring a bell?

In any case, this all looks great to me! I'll accept since @mxosman is out but he can take a look when he gets back.

**Comment by lilidworkin** [comment]
The fix with the label under the bars in the bar chart looks so good and was very clever!!

**Comment by terryttsai** [comment]
Yes I remember sending the dimensions over separately in the old API, though I no longer am with the new API. I just looked at the API payload and actually this is no longer an issue since we send over all the dimensions, even if there are no datapoints for them. This makes sense since this is similar to the metric config API.

So yeah, maybe the better fix would be for the backend to just not send datapoints with no values? Would that lead to any issues? Why are these datapoints being sent over in the first place? How much time should I spend digging into this, maybe I should write up a ticket to investigate this later?

**Comment by lilidworkin** [comment]
@terryttsai yea it doesn't seem especially high priority -- I think filtering out null datapoints is totally fine for now! Not sure why we're sending them and if omitting would break anything, would need to be investigated.

**Comment by terryttsai** [comment]
Made a ticket to investigate this: https://github.com/Recidiviz/justice-counts/issues/274

When I think about it, when you publish a report but some of the fields are not filled out, perhaps it's okay for those to show up as null values. So maybe this is expected? Is there any issue with the backend sending that over to the frontend?

**Comment by mxosman** [comment]
LGTM!

**Pull request merged**
