### PR TITLE
[Frontend] Fix filtering metrics in review metrics page

### LINKED ISSUE #27: [Frontend][Review Metrics] Fix filtering out datapoints with null values
**What needs to be done? Why does it need to be done?**
BtcJsQmw

ui5zpPFo
sercontent.com/5040739/191339442-c6aa7093-79fd-4053-99e0-6877918601f6.png)

Fix numbering if metrics were hidden due to having no datapoints with values

Don't allow navigating to this page if there are no datapoints to review

**Additional context**
Add any other context about the task here.

### PR DESCRIPTION
**Pull request by terryttsai**
## Description of the change

Filter out metrics we are getting in the data upload api response if there are no updated datapoints for that metric

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #27 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by mxosman — APPROVED** [review]
LGTM

**Comment by lilidworkin** [comment]
Thanks so much for the quick fix @terryttsai ! Two questions:
1) How does this affect the numbering? I imagine this will still cause the issue where now the numbers can start at, e.g. 4 instead of 1? Is that easy to fix? Totally fine to do that in a separate PR.
2) How does this look if there are 0 metrics with datapoints (e.g. if you upload a spreadsheet)? I know we're still debating the right behavior for this state, and might not even show this page in this case, but in the meantime, maybe we can add a little message to this state that says something like "Uh oh, no data was found in the spreadsheet."

**Comment by terryttsai** [comment]
This PR fixes the issue where the metric section number starts at, say, 4 instead of 1.

Right now, 0 metrics just say "Review 0 metrics" and the subtitle and the sections are empty.

We could render some sort of message on this page if there are 0 metrics to review for now, I'll take a stab at it.

**Comment by lilidworkin** [comment]
> This PR fixes the issue where the metric section number starts at, say, 4 instead of 1.
oh awesome!

> Right now, 0 metrics just say "Review 0 metrics" and the subtitle and the sections are empty. We could render some sort of message on this page if there are 0 metrics to review for now, I'll take a stab at it.

That would be great! Thank you!

**Pull request merged**
