### PR TITLE
Refactor toast component

### LINKED ISSUE #235: [Frontend][Common] Refactor Toast Component
The toast component that we use throughout Publisher is in sore need of a clean up refactor. It should have the same functionality, but instead of accepting 6 parameters, we can pass in something like an `options` object that will store all of the properties needed (along with setting defaults where appropriate).

This was originally implemented in vanilla JS (in haste) but does not need to be if there's a better implementation. The only thing we have to keep in mind is this function can be called from anywhere within the app and not exclusively in rendered components (e.g. you can call this within a function inside of a data store).

I haven't explored this yet - but I wondered if [React Portal](https://reactjs.org/docs/portals.html) would be a better option. It might not be if we want to have the flexibility of calling this from anywhere in the app.

### PR DESCRIPTION
**Pull request by ivan-kishko**
## Description of the change

> Description here
Refactor toast, change params to object, some other small cosmetic fixes

## Type of change
Type: Non-breaking refactor

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #235 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by lilidworkin** [comment]
Super exciting to see this @ivan-kishko ! I'm going to defer entirely to @terryttsai  and @mxosman  for review on this one since they know this part of the codebase WAY better than me :D

**Review by mxosman — APPROVED** [review]
@ivan-kishko - you are my hero! Thank you so much for cleaning up this toast component that used to make me cringe! I love how you reorganized everything - and especially love the style function (`getToastStyles`). Code looks great to me (way better than it was before)! 🙏  Will let @terryttsai take a look as well, but I'll approve this right now.

**Review by terryttsai — APPROVED** [review]
This looks fantastic, thanks for tackling this!

**Comment by terryttsai** [comment]
I agree w @mxosman, love how code is reused with functions like `getToastStyles` and `getAnimateProps`!

**Pull request merged**
