### PR TITLE
[Agency Dashboard] Remove slug from published data url for agency dashboards

### LINKED ISSUE #1444: [Agency Dashboard] Update URL for published data

### PR DESCRIPTION
**Pull request by nichelle-hall**
## Description of the change

Updates URL for published_data so that the FE an correctly fetch data to render the dashboard pages. I tested this manually by deploying the changes to staging with the BE changes and visiting the dashboard for various agencies. 

## Related issues

Closes #1444

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by lilidworkin — APPROVED** [review]
Fantastic, thanks!

**Review by mxosman — APPROVED** [review]
Awesome! Thank you for taking care of the FE, @nichelle-hall! 

Small nit (b/c it doesn't affect the current functionality and things are working as expected) but we're still using the slug in the FE routing and navigation. We could clean this up by removing the `slug` from `App.tsx` routes, `AgencyOverview.tsx` (but, keeping the `/${slugify(category)}`), and `Home.tsx` in L70 (removing the `/${encodeURI(agency.name)`).

**Review by morden35 — APPROVED** [review]

**Comment by nichelle-hall** [comment]
> Awesome! Thank you for taking care of the FE, @nichelle-hall!
> 
> Small nit (b/c it doesn't affect the current functionality and things are working as expected) but we're still using the slug in the FE routing and navigation. We could clean this up by removing the `slug` from `App.tsx` routes, `AgencyOverview.tsx` (but, keeping the `/${slugify(category)}`), and `Home.tsx` in L70 (removing the `/${encodeURI(agency.name)`).

I thought about removing it... I thought that it looked good aesthetically to have the name there. But there is no reason for it... 

I'll open up a follow-up PR to remove it + announce to CSG that there is a change. 

@lilidworkin any opinions / vetos on this? ^^

**Comment by lilidworkin** [comment]
@nichelle-hall @mxosman I actually think it might be better to leave it in the URLs so we don't break the dashboards for CSG! I mean those dashboards are essentially deprecating now and I'm not sure if they are using them, but I don't see a reason to make the change.

**Comment by nichelle-hall** [comment]
Ok! Sounds good @lilidworkin. And that's a good point. The whole point of this change is to help deprecate the current dashboard.

**Comment by mxosman** [comment]
Oh yeah - great call on all fronts - nevermind my nit! Thank you both for your thoughts on this!

**Pull request merged**
