### PR TITLE
Replace "system(s)" with "sector(s)"

### LINKED ISSUE #424: Rename "System" / "Systems" to "Sector" / "Sectors"
Wherever the word "system" (or "systems") appears in the UI, replace with "sector" (or "sectors").

### PR DESCRIPTION
**Pull request by ivan-kishko**
## Description of the change

> Change all appearances of "system(s)" to "sector(s)"  

## Type of change
Type: Non-breaking refactor 

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #424 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by mxosman** [comment]
Awesome, Ivan! Here are just a few others I noticed:
* Toast message in MetricConfiguration.tsx:
  * L90: `message: 'System "${systemSearchParam}" does not exist in "${currentAgency?.name}" agency.',`
* Toast message in MetricsView.tsx:
  * L98: `message: 'System "${systemSearchParam}" does not exist in "${currentAgency?.name}" agency.',`
  * L117: `message: 'Metric "${metricSearchParam}" does not exist in "${systemSearchParam}" system.',`
* Toast & error message in AgencyStore.ts
  * L149: `throw new Error("There was an issue updating the agency systems.");`
  * L153: `message: 'Agency systems saved.',`

**Comment by ivan-kishko** [comment]
> Awesome, Ivan! Here are just a few others I noticed:
> 
> * Toast message in `MetricConfiguration.tsx`:
>   
>   * L90: `message: 'System "${systemSearchParam}" does not exist in "${currentAgency?.name}" agency.',`
> * Toast messages in `MetricsView.tsx`:
>   
>   * L98: `message: 'System "${systemSearchParam}" does not exist in "${currentAgency?.name}" agency.',`
>   * L117: `message: 'Metric "${metricSearchParam}" does not exist in "${systemSearchParam}" system.',`
> * Toast & error message in `AgencyStore.ts`:
>   
>   * L149: `throw new Error("There was an issue updating the agency systems.");`
>   * L153: `message: 'Agency systems saved.',`

Hello @mxosman) check out this fixes [80e4e5b](https://github.com/Recidiviz/justice-counts/pull/429/commits/80e4e5bd154e738eb6309687cb31595aaa2f42e3)

**Review by mxosman — APPROVED** [review]
Thank you so much, Ivan! LGTM!

**Review by lilidworkin — APPROVED** [review]
Thanks @ivan-kishko !

**Pull request merged**
