### PR TITLE
Fix download template issue due to routing change

### LINKED ISSUE #297: [Frontend] Bulk upload templates not downloading properly
From Matt at CSG:

Weird thing I haven't seen before: trying to download the bulk data template from the upload page and I get an index.html file with the follwoing contents, rather than xlsx
```
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Web site created using create-react-app"/><link rel="apple-touch-icon" href="/logo192.png"/><link rel="manifest" href="/manifest.json"/><title>Justice Counts | Control Panel</title><script src="/app_public_config.js"></script><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"><script defer="defer" src="/static/js/main.817a9bda.js"></script><link href="/static/css/main.f2824c13.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
```
He was on this page:
https://justice-counts-web-qqec6jbn6a-uc.a.run.app/agency/152/upload

### PR DESCRIPTION
**Pull request by terryttsai**
## Description of the change

Fix not being able to download bulk upload templates, this is due to a routing change causing the href to be outdated. 

Perhaps we should add a test to make sure this link works to avoid future regressions?

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #297

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by terryttsai** [comment]
Deploying this fix to https://terrytest---justice-counts-web-qqec6jbn6a-uc.a.run.app/ to be able to test it there too

**Review by mxosman — APPROVED** [review]
Thank you, Terry!!!

**Comment by mxosman** [comment]
I like the idea of adding a small test to this! How would you write a test for something like this? Is it just checking the route - or that it downloads somehow?

**Comment by terryttsai** [comment]
I'm not sure what's the best way to test this, but with an absolute download path in place I don't foresee future problems unless we move/delete those files and then we'd probably be aware that that would break this feature, so I'll hold off on creating a test for this for now.

**Pull request merged**
