### PR TITLE
Nit #1: changes to metric availability page

### LINKED ISSUE #690: Nit #1: Changes to Metric Availability page
Item 1 in this [Figma File](https://www.figma.com/file/0UZOuDCrwGqWLKOhAyvGbc/Forrest's-First-Figma-File-(FFFF)?type=design&node-id=1173%3A45776&t=vmxUwNJ53SY7d0fk-1)

### PR DESCRIPTION
**Pull request by ivan-kishko**
## Description of the change

> Adjusting styles and adding button to metric availability page

## Type of change
Type: Non-breaking refactor

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #690 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by mxosman** [comment]
Code LGTM! 

Can we adjust the left margins/padding to make the toggles and define metrics -> button fully left-aligned?
Screenshot 2023-06-21 at 5 14 02 PM

Open question: for multiple disaggregations, are we OK with the Define Metrics -> button appearing under each disaggregation?
Screenshot 2023-06-21 at 5 17 40 PM

**Comment by ivan-kishko** [comment]
> Code LGTM!
> 
> Can we adjust the left margins/padding to make the toggles and define metrics -> button fully left-aligned? Screenshot 2023-06-21 at 5 14 02 PM
> 
> Open question: for multiple disaggregations, are we OK with the Define Metrics -> button appearing under each disaggregation? Screenshot 2023-06-21 at 5 17 40 PM

[6cf577d](https://github.com/Recidiviz/justice-counts/pull/721/commits/6cf577da2c08b8d85084d4e8be298455c0fdaa85). Here is the alignments, and I definitely think that duplicates of define metrics is my fault and not design intention so fixed it too)

**Review by mxosman — APPROVED** [review]
> [6cf577d](https://github.com/Recidiviz/justice-counts/pull/721/commits/6cf577da2c08b8d85084d4e8be298455c0fdaa85). Here are the alignments, and I definitely think that duplicates of define metrics is my fault and not design intention so fixed it too) That looks just more logically, but I guess @forrestkim00 to confirm just in case

Nice! Thank you for the adjustments, Ivan - they look great to me. I was mostly curious - but I feel like it makes sense to just have one `Define Metrics ->`.  Either way, we can adjust again if @forrestkim00 or others disagree - but this is good to merge!

**Comment by lilidworkin** [comment]
Yep I'm pretty sure only one Define Metrics! Thanks both!

**Pull request merged**
