### PR TITLE
Fix data page bug

### LINKED ISSUE #677: [Bug][Frontend] Sometimes when you click on the Data Viz page and click on another link, it briefly takes you to your destination and suddenly snaps you back to you back to the Data Viz page
There is a strange intermittent bug when you click to go to the Data (visualization) page and go to another page - there are moments when you get redirected back to the Data page. It doesn't happen all the time and there's no clear way to trigger this. Some times it takes a few seconds before you get snapped back, sometimes it happens immediately, sometimes not at all. It feels like there's something funny going on with either the routing or some state that the Data page updating after you leave that page. I was able to capture a video of this behavior happening a couple of times:

https://github.com/Recidiviz/justice-counts/assets/59492998/e3f46adf-2536-4182-b7c4-3ff8e849012e

### PR DESCRIPTION
**Pull request by ivan-kishko**
## Description of the change

> Fix bounce back data page bug

## Type of change
Type: Bug

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #677 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by ivan-kishko** [comment]
Hello to all! @mxosman @lilidworkin @alfonsogoberjr Want to comment about this PR. So while from user perspective everything good, no bounce back, if no enabled metrics you see "No enabled metrics" message, if system is not in agency or metric is not in system you see "Not Found", I dont really like my solution at all, cause if you look at it there is a lot of conditional rendering and you can easily get lost trying to find out what is going on. The main problem here that differs it from config page is that we have to identify not only system but also metric as well in order to render this page and all this mess comes from metricsBySystem. We use it to get current metric, but when you change agency before useEffect gets new metricsBySystem from api call, it tries to get metrics from old metricsBySystem with new system key. That is why you see what you see in the code. Not sure what to do about it right now

**Comment by mxosman** [comment]
Hi Ivan! Will take a closer look at this tomorrow - thank you for the effort and for your comment!

**Comment by mxosman** [comment]
I totally see what you're saying and running into. Let me think about this some more...

**Comment by mxosman** [comment]
OK - I was playing around with this and we might be able to solve it while keeping the conditionals less confusing.

What if we do something like this? https://github.com/Recidiviz/justice-counts/pull/860 
It's a rough sketch - I left some comments in-line, but let me know what you think.

**Comment by ivan-kishko** [comment]
So @mxosman @lilidworkin I merged Mahmoud's proposal, if you ok with that, I mean Lili, then you should merge this one to main)

**Review by alfonsogoberjr — APPROVED** [review]
LGTM

**Review by mxosman — APPROVED** [review]

**Pull request merged**
