### PR TITLE
[Justice Counts] Do not redefine SelectedFile on System Selection

### LINKED ISSUE #735: [Bug] Data Upload: Adjust `handleSystemSelection` so an uploaded file's name gets passed through to the review components
Reference playtesting discussion: https://docs.google.com/document/d/1tUCpwI2OX3B_gP4ZE4yo3ok304REOXcCc4mR15rq5nM/edit?disco=AAAAzpFWGmQ

**Issue**: For agencies with multiple systems, after uploading a file and viewing the Errors/Warnings page, when you click on `Continue` you are redirected to the Records page instead of the Review page.

**Why this is happening**:
The current assumption is the `handleSystemSelection` function within `DataUpload.tsx` (which gets called when a user selects which system they are uploading for) resets the `selectedFile` state and no file name is passed through to the `UploadErrorsWarnings` component and thus no file name is passed to the `UploadSpreadsheet` component.

```
  const handleSystemSelection = (file: File, system: AgencySystems) => {
    setIsLoading(true);
    setSelectedSystem(system);
    handleFileUpload(file, system);
    setSelectedFile(undefined); // <--- this resets the selectedFile state...
  };

  // ...which causes the below component to receive `undefined` for `fileName` 
  <UploadErrorsWarnings
    errorsWarningsMetrics={errorsWarningsMetrics}
    newAndUpdatedReports={newAndUpdatedReports}
    selectedSystem={selectedSystem}
    resetToNewUpload={resetToNewUpload}
    fileName={selectedFile?.name} // <--- `handleSystemSelection` now makes this `undefined`...
  />

  // ...which triggers this conditional in the `UploadSpreadsheet` component
  if (!uploadedMetrics || !fileName) {
    return <Navigate to={`/agency/${agencyId}/${REPORTS_LOWERCASE}`} replace />;
  }

```

**Solution**: Remove `setSelectedFile(undefined)` from the `handleSystemSelection` function assuming it is safe to do so and doesn't cause other undesired behavior. Since a user cannot go back and change systems after uploading and making a system selection, this should no longer be necessary.

### PR DESCRIPTION
**Pull request by morden35**
## Description of the change

Previously, when I user selected the system in which they wanted to upload a file for via Bulk Upload, we called setSelectedFile(undefined). This triggered a conditional that redirected the user to the reports page, rather than the bulk upload review page. By removing this line, we now go to the review page as expected.

Before:

https://github.com/Recidiviz/justice-counts/assets/82831800/8ab01578-9e66-4cdf-ae74-60026d6d58fa

Now:

https://github.com/Recidiviz/justice-counts/assets/82831800/5d507385-ff84-4b99-99e5-1b099e4aa1f4

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #735

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by nichelle-hall — APPROVED** [review]
🙌🏾

**Review by mxosman — APPROVED** [review]
Amazing!! Looks good to me! 🚀

**Comment by lilidworkin** [comment]
WOW @morden35 and @mxosman this was NEXT-LEVEL debugging. Great work!!!!

**Comment by morden35** [comment]
> WOW @morden35 and @mxosman this was NEXT-LEVEL debugging. Great work!!!!

All props truly go to @mxosman on this!

**Comment by mxosman** [comment]
This was 1,000% team effort - all thanks to both of your initial sleuthing!

**Pull request merged**
