### PR TITLE
deprecate denylist file, use denylist from DB

### PR DESCRIPTION
**Pull request by nichelle-hall**
## Description of the change

Uses the denylist value sent in the agency response to decide what agency dashboards to surface. 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by lilidworkin — CHANGES_REQUESTED** [review]
Re-request review when you add a test plan! Thanks so much for going ahead and making the FE changes too!

**Comment by nichelle-hall** [comment]
Here's my plan!

1. Deploy this code to playtesting
2. Manually change the enabled / disabled toggle for **Law Enforcement [DEMO]** dashboard in staging. 
Note: Is [this](https://docs.google.com/document/d/1AMq36vUvUIj_yEjNtjLbGFXjU8ttNk8u3MSqLRnHPoE/edit) sheet still up date for staging dashboards?
4. Manually check that this dashboard is enabled, but no other dashboards are. 
5. Finish enabling manually the staging agency dashboards.

**Comment by nichelle-hall** [comment]
As for backfilling the agencies in prod, I plan to write a quick script! Working on that now :)

**Comment by nichelle-hall** [comment]
@lilidworkin Tested this with my playtesting link and it worked like a charm!

**Comment by morden35** [comment]
> @nichelle-hall that sounds great! I think in staging we'll want to enable all dashboards eventually, though while testing you can obviously turn them on and off. You can go ahead and deploy this to playtesting before we merge it, so I'll hold off on accepting until you're able to do that full test! LMK how it goes

I made a comment about this [here](https://github.com/Recidiviz/recidiviz-data/pull/24613#discussion_r1355709043). I feel like maybe we should only enable 'DEMO' dashboards. wdyt?

**Comment by nichelle-hall** [comment]
> > @nichelle-hall that sounds great! I think in staging we'll want to enable all dashboards eventually, though while testing you can obviously turn them on and off. You can go ahead and deploy this to playtesting before we merge it, so I'll hold off on accepting until you're able to do that full test! LMK how it goes
> 
> I made a comment about this [here](https://github.com/Recidiviz/recidiviz-data/pull/24613#discussion_r1355709043). I feel like maybe we should only enable 'DEMO' dashboards. wdyt?

I think that's a good idea! I'll add that change now.

**Review by lilidworkin — APPROVED** [review]
Awesome @nichelle-hall , glad to hear it worked! And @morden35 you raise a great point about us possibly using real data in staging and therefore only ungating the DEMO agencies -- I agree! Awesome callout

**Pull request merged**
