### PR TITLE
[Publisher] Help Center: Add screenshots and entry point to Dashboards from Publisher

### LINKED ISSUE #1024: Update Help Center with ScreenShots
**What needs to be done? Why does it need to be done?**
Hi Mahmoud! Just created some screenshots to add to the help center. Here is the [Figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=9886%3A1553&mode=design&t=Ia5fEe9ZeJ8k2eX1-1) File.

**Additional context**
I'll set up a quick meeting to discuss how we can create the images to maintain resolution.

### LINKED ISSUE #1025: Create new dashboard link in publisher
**What needs to be done? Why does it need to be done?**
Hola! We are creating a link to Agency Dashboard from publisher. Here is the [Figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=9886%3A1555&mode=design&t=Ia5fEe9ZeJ8k2eX1-1)

**Additional context**
A couple notes that I left in the Figma as well: 
- This will link to whichever agency the user is currently in for Publisher.
- This link only exists if there is a live dashboard.
- Not dealing with the Superagencies edge case for now.

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

Adds screenshots to guides, entry point to Dashboards from profile dropdown (visible only if the agency has dashboards set to live), and updates which words are linked in each Guide per [Figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=9886%3A1553&mode=design&t=Ia5fEe9ZeJ8k2eX1-1) spec.

Play with it here: https://mahmoudtest---publisher-web-b47yvyxs3q-uc.a.run.app/

## Related issues

Closes #1025, Closes #1024 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by jwhrec** [comment]
The screenshots look amazing, thanks Mahmoud! I noticed this also has the updated text correct?

**Comment by mxosman** [comment]
> The screenshots look amazing, thanks Mahmoud!
> beautiful!

Thank you both! All thanks to Forrest for the beautiful screenshots! 

> I noticed this also has the updated text correct?

The text at the bottom of the playtesting doc was updated in this PR: https://github.com/Recidiviz/justice-counts/pull/1023

The only copy adjustments in this PR was removing extra links to Publisher within each guide - mimicking what the current [Figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=9886%3A1553&mode=design&t=Ia5fEe9ZeJ8k2eX1-1) has linked - if that makes sense. In #1023, I was following the playtesting doc instructions on which keywords to link within each guide - and this PR I removed the extra links to match the Figma. [Please LMK if I made the wrong assumption!]

**Comment by jwhrec** [comment]
I think that works perfectly, thanks for sorting this out Mahmoud! Everything looks great to me

**Review by lilidworkin — APPROVED** [review]
🙌

**Pull request merged**
